### ISSUE TITLE
contracts not completing

### ISSUE THREAD

**Issue by stebo1** [henkelmax/delivery-inc#1]
I'm playing this modpack and enjoying it so much.
There is just a problem with two of the quest/contract:
    One need to send a "mining turtle", i've tried with a mining turtle and with a normal turtle a couple of time each, the envelope get sent but the contract still result uncompleted.
    The other one need to send an image that capture "an upright pigs", I think it mean a zombified piglin but again the envelope get sent but the contract still result uncompleated (i tried sending an image with the zombified piglin in the middle, one with it in the nether and one with it in the overworld.

**Comment by henkelmax** [comment]
The mining turtle needs to be a normal turtle crafted together with a diamond pickaxe (Not the advanced mining turtle).
The pig quest text is maybe a bit too inaccurately worded. You need to send a picture of a piglin. We will change the text in a later update.

**Comment by henkelmax** [comment]
It should be fixed in 1.16.5-1.0.3
