### ISSUE TITLE
SolarFluxReborn

### ISSUE THREAD

**Issue by pjlasl** [henkelmax/delivery-inc#10]
I downloaded the latest version (1.0.21) and it is throwing an error when loading the client:

https://paste.ee/p/1FrO5

**Comment by henkelmax** [comment]
I tested it and it works fine. Have you added any mods or are you using another launcher?

**Comment by pjlasl** [comment]
I am using the zip file from curseforge. didn't change a thing to it.
I am using java 1.16.5. See log here: https://paste.ee/p/Q8Nab

**Comment by henkelmax** [comment]
You have to use the java version that is bundled with minecraft. You are using `Java Version: 15.0.2, AdoptOpenJDK`. Solar flux most likely uses Nashorn for scripting. This doesn't work with every Java version.

**Comment by pjlasl** [comment]
Interesting. I originally was using java 8, then i switched to adoptopen, then back to 1.8 and its working...go figure.
