### ISSUE TITLE
Client crashing when opening a contract

### ISSUE THREAD

**Issue by ThugPug43** [henkelmax/delivery-inc#11]
**Please make sure that this bug has not already been reported!**

**Only report bugs if this occurs in an unmodified and up-to-date version of the modpack!**

**Bug description**

**Steps to reproduce the issue**
1. Go to your mailbox and take a contract
2. Click on the contact to open it
3. Sometimes you will crash
4. Get an error when trying to connect to the server

**Expected behavior**
I expected to be able to open the contract without crashing, and normally can, this one crashed.

**Log files**

https://gist.github.com/ThugPug43/ad8005ef8b5dfbf4e90677c85d93ecf5

**Screenshots**

![image](https://user-images.githubusercontent.com/31190716/114291539-d44e6980-9a4d-11eb-8209-1a3d122cd8b5.png)

**Comment by ThugPug43** [comment]
I'm using unmodified version 1.0.21 of the pack

**Comment by henkelmax** [comment]
Unfortunately, I am not able to reproduce this issue. Can you try and find out with which contract exactly it crashes?
Please also try a clean install of the modpack.

**Comment by ThugPug43** [comment]
It was the one requesting a piglin picture. I also can't reproduce it. Before I did a clean install I couldn't join but after the clean install I can.

**Comment by henkelmax** [comment]
OK, please let me know if it happens again and I will reopen the issue.
