### ISSUE TITLE
Bees needing more unique blocks for pollination

### ISSUE THREAD

**Issue by leyxcx** [henkelmax/delivery-inc#12]
**Is your feature request related to a problem? Please describe.**
This is related to the issue with bees all being attracted to the same flower and not being able to pollinate consistently. 

**Describe the solution you'd like**
Would you consider making some changes to some of the bees making it so Iron bees need an iron block, etc? The problem _should_ be solved that way, at least I haven't many issues while I've been configuring the mod.

**Comment by henkelmax** [comment]
I made bees purposefully that simple, as it is a pain handling them.

You can use the honey dipper to assign bees to flowers:

![image](https://user-images.githubusercontent.com/13237524/115075492-6f868980-9efb-11eb-917b-e0c2b8b6df93.png)
