### ISSUE TITLE
Cannot complete drone contracts

### ISSUE THREAD

**Issue by DarrenShipley** [henkelmax/delivery-inc#13]
Modpack version 1.0.22. Cannot complete drone contracts. Items are submitted by drone but are not counted.

**Steps to reproduce the issue**
1. Put required items in cardboard box.
2. Insert proper upgrade into drone pad.
3. Put cardboard box into drone pad.
4. Wait for it to leave and return.
5. See that contract has not progressed or completed.

**Comment by henkelmax** [comment]
Did you accept the contract?

**Comment by DarrenShipley** [comment]
Yes

**Comment by henkelmax** [comment]
Which exact contract do you want to submit?

**Comment by henkelmax** [comment]
I tried it myself and it works perfectly fine.

**Comment by DarrenShipley** [comment]
I tried the 1k sugar and 256 logs. Both didn't work for me. Delivering 16 sugar in a parcel did partially complete it though.

**Comment by henkelmax** [comment]
Please execute this command: `/group backup create` and send me the file located in you world folder in `progression_backups`.

**Comment by DarrenShipley** [comment]
[2021-04-19-13-41-26-270.zip](https://github.com/henkelmax/delivery-inc/files/6338635/2021-04-19-13-41-26-270.zip)

**Comment by henkelmax** [comment]
I tested it with your quest again and it works.
Please make sure that you completely read and understood the manual.

Also make sure that the drone isn't crashing back down or obstructed by something.

**Comment by DarrenShipley** [comment]
Thanks for trying. I understand the manual, the drone isn't crashing down, and there are no obstructions above.

It may be because I enabled dimension stack on my world, although there is no land or anything else directly above the drone pads.
