### ISSUE TITLE
"Could not find a new task for group!"

### ISSUE THREAD

**Issue by SlainChops** [henkelmax/delivery-inc#15]
**Bug description**
We just recently finished a task requesting Biofuel & have not received another email contract in quite some time. I checked our server console and the delivery mod keeps warning us that it cannot find another task for our group to complete. Have we simply finished all that is available or have we encountered some kind of error?

**Log files**
I've included just today's logs because it shows the same warning over and over. I can send more logs if need be.
https://gist.github.com/SlainChops/c061183abfd4f213977dc00b6b26d5a9

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/83758640/117276415-bccb8c00-ae13-11eb-8fd1-64b7fff2bf91.png)

**Comment by henkelmax** [comment]
Please make sure, you don't have any unaccepted contracts in your emails

**Comment by SlainChops** [comment]
We currently have no unread emails.
![image](https://user-images.githubusercontent.com/83758640/117277925-26986580-ae15-11eb-9467-7634a81ba3dd.png)

**Comment by henkelmax** [comment]
Please type the command `/group backup create` and send me the `.dat` file located in your world folder in `progression_backups`

**Comment by SlainChops** [comment]
Should I be able to input that command via the server console?

**Comment by SlainChops** [comment]
> Please type the command `/group backup create` and send me the `.dat` file located in your world folder in `progression_backups`

https://drive.google.com/file/d/1I360kHm9VotGJ1MBj1aiyz7f_hzkDlVF/view?usp=sharing I hope a drive link is okay.

**Comment by henkelmax** [comment]
![image](https://user-images.githubusercontent.com/13237524/117367437-797c2680-aec2-11eb-84f3-074b64f57c8d.png)

You clearly didn't accept the first two contracts in your E-Mails
