### ISSUE TITLE
Command Strings for Group Creation

### ISSUE THREAD

**Issue by SlainChops** [henkelmax/delivery-inc#16]
I added Server Utilities Mod to my server to help my friends get around a bit better. It works on a rank system & in order for them to be able to create groups, join groups, etc, I need to give them permission to execute these commands.

Would you be able to send me a list of basic command strings commonly used with the Delivery Mod?

**Comment by henkelmax** [comment]
You can read the manual for the group commands. Everything else is self explanatory with command completion

**Comment by SlainChops** [comment]
I see the commands in the manual, but I need the strings. Like how /gamemode is minecraft.command.gamemode, or how /spawn is serverutils.spawn. Does the delivery mod generate a file where I could find these?

**Comment by henkelmax** [comment]
I don't think there are such strings in the mod.

**Comment by SlainChops** [comment]
It took some digging, but the correct word for what I'm looking for is called a Permission Node. I'm going to keep looking to see if they're listed anywhere.

**Comment by henkelmax** [comment]
I didn't define any in the code, but I can look into it.

**Comment by henkelmax** [comment]
> *edit: We've got it working for now. Sorry for all the hassle and ty for the help

So do you still need the permission nodes?
