### ISSUE TITLE
Chorus fruits are extremely rare

### ISSUE THREAD

**Issue by LemADEC** [henkelmax/delivery-inc#17]
**Bug description**
Chorus fruits are next to impossible to find the end, even End cities hardly spawn due to modded biomes changes

**Steps to reproduce the issue**
1. Go to TheEnd
2. Kill the dragon
3. Try to find a Chorus fruit

**Expected behavior**
Find a lot of chorus fruits on every other big island, like vanilla.

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/4776032/118343529-eda17480-b529-11eb-932c-78b44a417a07.png)
That's 3k x 3k surface we had to explore before finding 3 cities and 5 Chorus fruit (yes, just 5 trees).
In Vanilla, we would have ~7 cities in the same surface.

Consider updating End agglomeratio ingredient to remove the Chorus fruit, so at least we can unlock chorus fruit after finding a city.

**Comment by henkelmax** [comment]
I found a chrorus fruit before finding the first end city. Yes, they are more rare because of BYG, so you rather want to report it to them.
