### ISSUE TITLE
Thermal Series and Resourceful Bees Create Infinite Power and Make Resourceful Bees too Easy!

### ISSUE THREAD

**Issue by Nortalian** [henkelmax/delivery-inc#18]
**Only report bugs if this occurs in an unmodified and up-to-date version of the modpack!**
Version 1.0.27
**Bug description**
Vanilla Recipe for Honeycomb Block is 2x2. Resourceful Bees changes it to 3x3.
Thermal Series' Multiservo Press still uses the 2x2 recipe (4 Honeycomb). Placing the Honeycomb block into any crafting window creates 9 honeycomb.

This can be repeated infinitely, turning each Honeycomb block into 2.25 more.

With the Honey Generator, this can create infinite RF, and makes crafting Hive 2-4 easy.

**Steps to reproduce the issue**
1. Make and Power Multiservo Press with Packing Die (2x2)
2. Place 4 Honeycomb into Multiservo Press
3. Collect 1 Honeycomb Block
4. Place Honeycomb Block into player's crafting grid (or any standard crafting window)
5. Collect 9 Honeycomb
6. Repeat Steps 2-5 for infinite Honeycomb

**Expected behavior**
Thermal Series' Honeycomb Block recipe needs to be updated to use the Packing Die (3x3) and require 9 Honeycomb to make a block.

**Log files**
Do I need to do this? It's not technically a bug in the traditional sense, just the mods not talking to each other.

**Screenshots (Optional)**
![2021-06-11_00 06 55](https://user-images.githubusercontent.com/29679536/121652240-4c3a0f80-ca50-11eb-9196-af6552d3ca78.png)

**Comment by henkelmax** [comment]
Thank you for reporting this issue. It should be fixed in the next version.
