### ISSUE TITLE
Iron got destroyed after being blown up

### ISSUE THREAD

**Issue by ChromaPIE** [henkelmax/delivery-inc#19]
When trying to make Compressed Iron Ingots, vanilla iron ingots would be destroyed by the explosion instead of triggering the transmutation.

**Comment by henkelmax** [comment]
This seems to be an issue of pneumaticcraft.
Please report this to their issue tracker.
Please also make sure that it is really not working, since a percentage of the iron always gets lost.

**Comment by ChromaPIE** [comment]
Okay and thanks for the instant reply. I've already confirmed in various ways that it's not working on my end. I'll report it there.

**Comment by ChromaPIE** [comment]
It's noticeable that there must be a mod or a feature seemingly causing every single blocks broken by explosions to drop themselves, that is to say, none of them got voided, and this is the only non-vanilla and the most sus behavior witnessed that is related to explosion. So any idea what it is? Dev of PNC have promised a check on whether and how it relates.
