### ISSUE TITLE
Quark Constantly Reloads config, inevitably spamming game console(Modpack Version 1.0.5)

### ISSUE THREAD

**Issue by Enderborn1235** [henkelmax/delivery-inc#2]
**Please make sure that this bug has not already been reported!**

**Only report bugs if this occurs in an unmodified and up-to-date version of the modpack!**

**Bug description**
Quark Constantly reloads config for some reason
**Expected behavior**
Quark wouldn't constantly reload 

**Log files**
See attached for crafttweaker and game logs
[latest.log](https://github.com/henkelmax/delivery-inc/files/6104698/latest.log)
[crafttweaker.log](https://github.com/henkelmax/delivery-inc/files/6104700/crafttweaker.log)

**Comment by henkelmax** [comment]
Should be fixed in the next version.
