### ISSUE TITLE
Unbalanced recipe for Refined Obsidian Dust

### ISSUE THREAD

**Issue by ChromaPIE** [henkelmax/delivery-inc#20]
Refined Obsidian Dust can be made from infusing diamond to both Obsidian Dust from Mekanism and Obsidian Shard from MoreVanillaLib, but:

- Obsidian Dust requires Enrichment Chamber and there will be 4 dusts for each Obsidian block, which makes sense because there should be enough sources for players to make some when it's required by contracts.
- Obsidian Shard can be obtained directly from crafting Obsidian blocks in the grids, and 9 for each block, which should be removed.

Also, there's a way to duplicate obsidian blocks: 1 Obsidian to 9 shards in crafting grids, 4 shards to 1 obsidian in Mekanism's Combiner.

**Comment by henkelmax** [comment]
Thank you for reporting this!
