### ISSUE TITLE
Quark Dragon Scales unobtainable

### ISSUE THREAD

**Issue by gaminggirl** [henkelmax/delivery-inc#24]
**Bug description**
For one of the last (after the end of the pack) quests you need 10 elytras, in JEI there is a recipe using Quark Dragon Scales to duplicate elytras so you do not have to go find 10 End Boats with an Elytra (managed to find like 4 in a month)

**Steps to reproduce the issue**
1. Look for recipe for Quark Dragon Scale
2. get sad.

**Expected behavior**
Maybe change recipe to use Mystical Agraditions Draginscale so that are obtained from the dragon.

**Log files**
Nothing in the logs about this

**Comment by henkelmax** [comment]
This item is obtained by killing the ender dragon.

**Comment by gaminggirl** [comment]
> 
> 
> This item is obtained by killing the ender dragon.

No it gives Mystical Agradition Dragonscale not Quark Dragonscale

**Comment by henkelmax** [comment]
https://ftb.fandom.com/wiki/Dragon_Scale
