### ISSUE TITLE
PneumaticCraft Drones not working

### ISSUE THREAD

**Issue by StanTheCarpenter** [henkelmax/delivery-inc#25]
**Bug description**
Drones from PneumaticCraft (all types; programmed drones, harvester drones, guard drones, collector drones etc) don't do their jobs. It's possible to deploy them and they will recharge at charging stations with a dispenser upgrade, but other than that they simply hover in place and do nothing. Pushing, hitting, redeploying them does not work. The range to their work area, chests or chargers does not seem to matter as the issue persists when they are deployed on top of or next to the area, chest or charger. 

**Steps to reproduce the issue**
1. Take any type of drone
2. Make sure it has a job/programming
3. Make sure it is charged
4. Place it down
5. Observe the drone hovering without doing anything.

**Expected behavior**
A collector drone, for example, should move to any dropped items within a 17x17x17 area, grab it, and move it to a nearby chest.

**Screenshot**
![2021-07-03_15 49 51](https://user-images.githubusercontent.com/66203777/124356470-69f53180-dc16-11eb-8c1d-8db9fae3fbd8.png)

Screenshots of the issue. Harvesting drone idling next to harvestable wheat and an empty chest. Drone is charged.

**Comment by henkelmax** [comment]
Pneumaticcraft drones are disabled in this modpack.

**Comment by StanTheCarpenter** [comment]
Ah, I see. Should their crafting recipes be removed, in that case?

**Comment by henkelmax** [comment]
> Ah, I see. Should their crafting recipes be removed, in that case?

They should be.
Maybe they got changed in some update of the mod
