### ISSUE TITLE
Missing Info in Tooltips

### ISSUE THREAD

**Issue by Ralsch** [henkelmax/delivery-inc#27]
Greetings.

Maybe it's a dumb problem, but I can't find any solution for this with Google.

When hovering above the Cardboard Boxes (or Barrels, Parcel, etc.) there should be an info about the capacity of the item.
Like:
***
Parcel
16 Items
Delivery
***

I only get:
***
Parcel
Delivery
***

So... what the heck am I doing wrong?
Surely it's something obvious... but what?

Thanks in advance.

**Comment by henkelmax** [comment]
This tooltip is only shown when having items in them.
