### ISSUE TITLE
Can't complete contract

### ISSUE THREAD

**Issue by Apollo2203** [henkelmax/delivery-inc#28]
**Please make sure that this bug has not already been reported!**

**Only report bugs if this occurs in an unmodified and up-to-date version of the modpack!**

**Bug description**
When trying to complete the Scuba Steve dolphin photo request, it takes the envelope but never removes the quest from the bulletin board. I've tried everything. Even spawning a dolphin and taking a photo.

**Steps to reproduce the issue**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
I expected the contract o be completed

**Log files**
Please provide log files of the game session in which the problem occurred.
Don't paste the complete logs into the issue.
You can use [https://gist.github.com/](https://gist.github.com/).
I created the backup log but don't know where to find it

**Screenshots (Optional)**
Screenshots of the issue.

**Comment by henkelmax** [comment]
Please fill out the complete bug template.
Also please make sure the dolphin is in the center of the frame.

**Comment by Apollo2203** [comment]
Bug description
When trying to complete the Scuba Steve dolphin photo request, the mailbox takes the envelope but never removes the quest from the bulletin board. I've tried everything. Even spawning a dolphin and taking a photo. Also tried putting almost 100 dolphins in a hole in creative and filling the entire camera frame with dolphins. I’ve done zoomed in photos in the center, normal photos in the center, dolphins underwater, dolphins jumping, etc. I’ve taken at least 50 photos trying to get this to work.

Steps to reproduce the issue
Get the dolphin task
take photos of dolphins
submit the photo in the mailbox
see the contract doesn’t complete

Expected behavior
I expected the contract to be completed

Log files
I created the group backup log but don't know where to find it

**Comment by henkelmax** [comment]
Does the quest work in singleplayer?

**Comment by Apollo2203** [comment]
How would I check? Is there a way to download all of my progress and put it into a single player world?

**Comment by henkelmax** [comment]
Yes, by exporting and importing the groups

**Comment by Apollo2203** [comment]
Where are all of the group files located?

**Comment by Apollo2203** [comment]
Is there a way to just manually skip the task? Like use a command? It's just annoying considering I always have that contract on my board and can't replace it. And because it isn't item-based, I have to rely on the actual camera instead of being able to cheat the item in in creative if it gets bugged again.

**Comment by henkelmax** [comment]
`/delivery complete_task <TASK-ID>`

**Comment by henkelmax** [comment]
Can you send me a screenshot of the contract?

**Comment by Apollo2203** [comment]
![unknown](https://user-images.githubusercontent.com/25265111/140380089-7f343142-b9db-4e72-98cf-1faa21c1b4cb.png)

**Comment by Apollo2203** [comment]
I tried /delivery complete_task and it says the "complete_task" part is an invalid argument.

**Comment by henkelmax** [comment]
`/delivery complete_task edb577e0-608e-11eb-ae93-000000000009`

You have to be OP

**Comment by Apollo2203** [comment]
The command won't work, I'm opped and it said invalid argument, and I pasted it in the console and it still said that.
<img width="1313" alt="Screen Shot 2021-11-04 at 11 45 16 AM" src="https://user-images.githubusercontent.com/25265111/140382525-2e364373-56cf-427f-a10b-4c93ef6eb839.png">

**Comment by henkelmax** [comment]
You need to execute it as a player in a group, obviously. How would it figure out in which group you are?

**Comment by aqEmerald** [comment]
friend and also in the same group as him here. I opped myself and ran the command. its actually /delivery test task_complete but I'm not sure how to find the id. and when I ran the command as just that, it completed a task we didn't have. I understand its "test" but there's still no way to make the command work without it.

**Comment by Apollo2203** [comment]
Okay, I also did it myself, as an admin, with OP, in-game, and it didn't work either. Also, the next camera task for the cherry blossom task also isn't working
<img width="269" alt="Screen Shot 2021-11-04 at 12 13 55 PM" src="https://user-images.githubusercontent.com/25265111/140387239-4b2c2dff-3fbc-4bf5-8a06-8c7001868a93.png">
g.

**Comment by Apollo2203** [comment]
> friend and also in the same group as him here. I opped myself and ran the command. its actually /delivery test task_complete but I'm not sure how to find the id. and when I ran the command as just that, it completed a task we didn't have.

Nah I already did that that doesn't have anything to do with this

**Comment by henkelmax** [comment]
I already sent you the ID https://github.com/henkelmax/delivery-inc/issues/28#issuecomment-961218486

**Comment by Apollo2203** [comment]
<img width="556" alt="Screen Shot 2021-11-04 at 12 16 27 PM" src="https://user-images.githubusercontent.com/25265111/140387501-1cee65bb-9c36-414b-b685-d30e77b9a4e0.png">

**Comment by Apollo2203** [comment]
<img width="649" alt="Screen Shot 2021-11-04 at 12 16 19 PM" src="https://user-images.githubusercontent.com/25265111/140387558-2710524e-a1da-4552-a2b9-129224e023fb.png">

**Comment by henkelmax** [comment]
Please send me the file located in `<your server dir>/world/serverconfig/camera-server.toml`

**Comment by Apollo2203** [comment]
Github won't support that file type, uploading to Drive.

**Comment by Apollo2203** [comment]
https://drive.google.com/file/d/1Oa3Fpt9ysuE-RH1ZJED26zlHf5Vf2TfL/view?usp=sharing

> Github won't support that file type, uploading to Drive.

**Comment by henkelmax** [comment]
I know your issue. You didn't install the server correctly. Just putting the mods on the server won't work. You need to actually install the server pack that is provided on Curse

**Comment by Apollo2203** [comment]
I did that. I downloaded the server pack, used the install.bat file, and moved the corresponding files over.

**Comment by henkelmax** [comment]
> I did that. I downloaded the server pack, used the install.bat file, and moved the corresponding files over.

Your configs are definitely not from the server pack.

**Comment by Apollo2203** [comment]
I moved mods, scripts, config, the server jar into the /jar root folder, and the forge jar into the /jar folder and renamed to custom.jar.

**Comment by Apollo2203** [comment]
This is the folder from which I took the other folders. https://drive.google.com/drive/folders/1Wsx3EG4d8_9m7UZIIHp_1TSEfC9DLjzU?usp=sharing

**Comment by henkelmax** [comment]
That's not correct. The most important part is to move the defaultconfigs folder.
You need to completely reinstall the modpack and delete your world, as the modpack completely breaks when not being configured correctly.

**Comment by Apollo2203** [comment]
aight. damn

**Comment by aqEmerald** [comment]
https://www.curseforge.com/minecraft/modpacks/delivery-inc/files 
is where it came from
we ran the install.batch and dragged the files and did the stuff we were told from apexhosting. it is most definitely from curseforge.

**Comment by Apollo2203** [comment]
> https://www.curseforge.com/minecraft/modpacks/delivery-inc/files
> is where it came from
> we ran the install.batch and dragged the files it made into the server from there. it is most definitely from curseforge.

no. we never uploaded the default configs folder

**Comment by aqEmerald** [comment]
> > https://www.curseforge.com/minecraft/modpacks/delivery-inc/files
> > is where it came from
> > we ran the install.batch and dragged the files it made into the server from there. it is most definitely from curseforge.
> 
> no. we never uploaded the default configs folder

i was never told this info i apologize

**Comment by Apollo2203** [comment]
Do you have a list of every file or folder I need to transfer? I didn’t see a pdf or txt

**Comment by henkelmax** [comment]
Just everything

**Comment by Apollo2203** [comment]
Do those individual files just go into the root? and what about the pack menu folder?

**Comment by henkelmax** [comment]
this directory IS the server

**Comment by Apollo2203** [comment]
Ok, I’ll just copy it all over. Maybe as a suggestion, because not everyone naturally knows this information, maybe add a simple readme? It would help a lot.

**Comment by Apollo2203** [comment]
I tried uploading the whole folder after running both .bat files, and I get this error message. I've literally ran both installers, I'm not sure what I'm expected to do here.
<img width="1097" alt="Screen Shot 2021-11-04 at 3 36 50 PM" src="https://user-images.githubusercontent.com/25265111/140416118-47d435ca-8b15-4650-b685-cde0432d6e4f.png">

**Comment by Apollo2203** [comment]
These are all the files in the directory.

<img width="587" alt="Screen Shot 2021-11-04 at 3 37 47 PM" src="https://user-images.githubusercontent.com/25265111/140416270-2c261d20-6672-4a7c-8e32-b76636438724.png">

**Comment by henkelmax** [comment]
Please ask your hoster on how to install modpacks. This process os different for every hoster.
But running the installer on windows might not work for a linux server.

**Comment by Apollo2203** [comment]
I got it figured out, the library folder had to be IN the jar folder with the renamed forge jar and server jar. Just in case you run into anybody else with a similar issue, that's what worked for me!
