### ISSUE TITLE
Server zip don't contain mods. 

### ISSUE THREAD

**Issue by demethan** [henkelmax/delivery-inc#3]
Hi, 

Usually, the server zip contains the mods with it.  This is really inconvenient. 

Thanks.

**Comment by henkelmax** [comment]
> Hi,
> 
> Usually, the server zip contains the mods with it. This is really inconvenient.
> 
> Thanks.

This is intended, since I have no rights to distribute these mods. The mods get automatically installed once you run the install script. I see no inconvenience there.
