### ISSUE TITLE
forge

### ISSUE THREAD

**Issue by SuperFurias** [henkelmax/delivery-inc#30]
**Is your feature request related to a problem? Please describe.**
I needed to update forge manually to start the pack
**Describe the solution you'd like**
update forge, for example to 36.2.0
**Describe alternatives you've considered**
idk, another recent version
**Additional context**
none

**Comment by henkelmax** [comment]
Why do you need to upgrade forge?

**Comment by SuperFurias** [comment]
As already mentioned, I had to update forge manually to start the pack, Multimc didn't have some libraries for 36.1.0
It's a request, you can very well refuse it, but wouldn't it be better to have a version of Forge updated?

**Comment by henkelmax** [comment]
That seems to be an issue with multimc. I deliberately chose this forge version, because it is the most stable with the mods that are in the pack.

**Comment by SuperFurias** [comment]
If there is this version for a specific reason in the pack, then I'm nobody to force you to change it , mine was just a suggestion
