### ISSUE TITLE
some stuff

### ISSUE THREAD

**Issue by SuperFurias** [henkelmax/delivery-inc#31]
**Is your feature request related to a problem? Please describe.**
Yes, claiming, setting, and personalizating
**Describe the solution you'd like**
Please install mod FTB Library, I can't configure jei without it (even if I think it's more like a bug)
Please install Game Menu Mod Option [Forge], otherwise I have to go out and return to the world each time to configure the mods options
You added the ftb chunks, but you didn't give the chance of claiming nor chunkloading the chunks (yes, the world is in cheat mode on), did you only put it for the minimap? The FTB Teams should be placed for interactions between blocks without need to whitelist them otherwise, admitted you give the possibility to players to claim, but if the possibility was removed, do I think there is some specific reason? 
**Describe alternatives you've considered**

**Additional context**
Jei Settings
![image](https://user-images.githubusercontent.com/34806112/141687558-abd9f317-774b-4213-bf98-0f1513bed737.png)
FTB Chunks
![image](https://user-images.githubusercontent.com/34806112/141687680-e3ff52a4-b10a-4164-89e2-56928c7a1a92.png)

**Comment by SuperFurias** [comment]
I ask forgiveness for the bad English

**Comment by henkelmax** [comment]
FTB chunks is only in there for the map, since at the time of creation there was no better map.
I deliberately disabled everything else like land claiming, since it is very buggy in combination with some mods.
If you want to enable this functionality, do it, but it won't be in the official pack.

**Comment by SuperFurias** [comment]
the FTB Library and Game Menu Mod Option [Forge] suggestion?

**Comment by henkelmax** [comment]
I see no benefits in these mods. I deliberately added as few mods as possible to this pack.
