### ISSUE TITLE
Crash with Optifine

### ISSUE THREAD

**Issue by LeafyLuigi** [henkelmax/delivery-inc#35]
This bug occurs in a modified version with one added mod: Optifine.
I completely understand if this issue is closed without any second guesses but please put a warning on the page. I have used both the CurseForge and the stock Minecraft launcher as a test to see if the launcher has any difference. I tried to emulate both situations as close to each other as possible. I am aware of how unstable Optifine can be though.

**Bug description**
Crash on startup with Optifine installed.

**Steps to reproduce the issue**
1. Install Optifine with the pack, version used is 1.16.5 HD U G8
2. Put Optifine into the mods folder
3. Run the game

**Expected behavior**
I did not expect a crash. I think that's a fair assessment on this situation.
Both launchers caused a crash.

**Log files**
[Log from CF Launcher](https://gist.github.com/LeafyLuigi/805bc52143cef633f74b55575fcb6c43)
[Log from Stock Launcher](https://gist.github.com/LeafyLuigi/dbeb672629dbd3582b5a7702b1e90505)
[debug.log from Stock](https://gist.github.com/LeafyLuigi/6bef784f5ff17a444330de40d23dcd1c)

**Comment by henkelmax** [comment]
This article shows why you shouldn't use Optifine (Ignore that the alternatives shown are for Fabric):
https://lambdaurora.dev/optifine_alternatives/

And in general we don't provide support if you modify the modpack. Especially when adding a mod that has the worst compatibility in Minecraft modding history.
