### ISSUE TITLE
What is the newest version?

### ISSUE THREAD

**Issue by thggs** [henkelmax/delivery-inc#4]
I've been playing this modpack with a friend for a while, and would like to know what is the current, most recent version

Because the Beta version is 1.0.8 and the Alpha is at 1.0.11. From my understanding the Beta version is supposedly the most recent, but the Alpha is at a higher version number. So which one is it?

**Comment by henkelmax** [comment]
No. This has nothing to do with beta or alpha. The highest version number is the latest version.
The alpha versions are just a little more unstable/untested.

**Comment by thggs** [comment]
Should I play the newest version or the more stable one? Because I can't get Optifine to work on 1.0.8, and I read a comment on Curse that it works in 1.0.9 onward

**Comment by henkelmax** [comment]
I wouldn't recommend using optifine in this modpack at all.
The compatibility between mods and optifine gets worse and worse in my opinion.
