### ISSUE TITLE
Error downloading modpack from curseforge

### ISSUE THREAD

**Issue by Andy04671** [henkelmax/delivery-inc#40]
I'm trying to download the modpack from curseforge, but when it finishes downloading it gives me this error

"Couldn't find part of the path '\\?\C:\Users\user\curseforge\minecraft\Instances\Delivery Inc.\minecraftinstances.json'. The problem it gives me is when I try to download this modpack

**Comment by henkelmax** [comment]
This modpack is no longer actively developed or maintained.
