### ISSUE TITLE
Industrial forgoing  - need update. 

### ISSUE THREAD

**Issue by demethan** [henkelmax/delivery-inc#5]
Hi, 

https://github.com/InnovativeOnlineIndustries/Industrial-Foregoing/issues/1061

We can`t use the Mod Duplicator because the version of Industrial Forgoing (3.2.10.1) contains a bug.  it is fixed in the newer versions 3.2.10.2.  

Thanks.

**Comment by henkelmax** [comment]
Thank you for reporting this issue. It should be updated in the next version.
