### ISSUE TITLE
Mod requests

### ISSUE THREAD

**Issue by excodex** [henkelmax/delivery-inc#8]
Hey,

I love the idea of this modpack built around the Delivery mod. I feel like missing something, so I would like to suggest some mods that makes the life a bit easier.

- [FTB Essentials](https://www.curseforge.com/minecraft/mc-mods/ftb-essentials) - nice to have on server commands
- [Modular Routers](https://www.curseforge.com/minecraft/mc-mods/modular-routers) - handy item manipulation without RF
- [Pedestals](https://www.curseforge.com/minecraft/mc-mods/pedestals) - it can be a cobblestone generator (I know there is already) and ore duplication etc.
- [Bad Wither No Cookie - Reloaded](https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded) - I don't really want to hear every time when Ender Dragon dies
- [Ensorcellation](https://www.curseforge.com/minecraft/mc-mods/ensorcellation) - powerful enchants
- [Flux Networks](https://www.curseforge.com/minecraft/mc-mods/flux-networks) - a way to charge items in inventory and transfer RF wirelessly
- [Dank Storage](https://www.curseforge.com/minecraft/mc-mods/dank-storage) - when I'm mining, it is easier to collect cobblestone and don't fill my inventory
- [Spice of Life: Carrot Edition](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition) - additional hearts 
- [TrashSlot](https://www.curseforge.com/minecraft/mc-mods/trashslot) - if you don't like the Dank, it's an alternative for that

**Comment by henkelmax** [comment]
FTB Essentials - Most of these commands are already in vanilla or doable with some mods. You also don't need commands if you play survival.
Modular Routers - Pipez is already very powerful / You also have Refined storage
Pedestals - We considered this mod, but we hat some problems with it.
Bad Wither No Cookie - Reloaded - We have the sound muffler mod
Ensorcellation - This modpack isn't about enchantments and stuff
Flux Networks - We have the quantum entangloporter
Dank Storage - Sophisticated backpachs does exactly that
Spice of Life: Carrot Edition - Obsolete with the meka suit
TrashSlot - There are trash cans in this modpack

**Comment by excodex** [comment]
Okay I understand your points. But can you tell me how can I charge my inventory? The Quantum Entangloporter does not do that. 

Also I would like to suggest a last one: [Glassential](https://www.curseforge.com/minecraft/mc-mods/glassential)

**Comment by henkelmax** [comment]
The meka suit has such a feature.

> Also I would like to suggest a last one: Glassential

This modpack isn't about decoration stuff and building. I want to keep it as small as possible while still having great tech mods.
