### ISSUE TITLE
group mod sets password to group name

### ISSUE THREAD

**Issue by mote** [henkelmax/delivery-inc#9]
this was in version 1.0.10, not sure if it's in others

**Bug description**
Somewhere, group password gets set to the group name

**Steps to reproduce the issue**
1. Teammate creates a group with a name and a password
2. (time passes, server resets, though not sure if this is necessary for the bug to occur)
3. I try to join the group with the original password
4. It doesn't work. But it does work when I join with the group name as the password

**Expected behavior**
password should be the password

**Log files**
none available

**Screenshots (Optional)**
none

**Comment by henkelmax** [comment]
Thank you for reporting this issue!
It should be fixed in the next version.
